name: Build LaTeX CVs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_latex:
    name: Build PDF CVs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    strategy:
      matrix:
        include:
          - cvlang: "DE"
            jobname: "Lebenslauf_Sven_Bergmann"
          - cvlang: "EN"
            jobname: "Curriculum_Vitae_Sven_Bergmann"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        run: pdflatex "--job-name=${{ matrix.jobname }} \def\cvlang{${{ matrix.cvlang }}} \input{cv.tex}"

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            Lebenslauf_Sven_Bergmann.pdf
            Curriculum_Vitae_Sven_Bergmann.pdf

  # --- Release Job ---
  # Creates a GitHub Release and attaches the PDFs (only runs on tag pushes)
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_latex
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download PDF artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: cv-pdfs

      - name: Create Release and Upload PDFs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Lebenslauf_Sven_Bergmann.pdf
            Curriculum_Vitae_Sven_Bergmann.pdf
          name: Release ${{ github.ref_name }}
          body: |
            CV Release for version ${{ github.ref_name }}
            Includes German and English CVs.
          draft: false
          prerelease: false