name: Build LaTeX CVs
on:
  push:
    branches:
      - master
  tags:
    - "*"
  workflow_dispatch:

jobs:
  build_latex:
    name: Build PDF CVs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    strategy:
      matrix:
        include:
          - cvlang: "DE"
            jobname: "Lebenslauf_Sven_Bergmann"
          - cvlang: "EN"
            jobname: "Curriculum_Vitae_Sven_Bergmann"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX document
        run: pdflatex -jobname=${{ matrix.jobname }} "\def\cvlang{${{ matrix.cvlang }}} \input{cv.tex}"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.jobname }}
          path: ${{ matrix.jobname }}.pdf

  # --- Release Job ---
  # Creates a GitHub Release and attaches the PDFs (only runs on tag pushes)
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_latex
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - jobname: "Lebenslauf_Sven_Bergmann"
          - jobname: "Curriculum_Vitae_Sven_Bergmann"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download PDF artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.jobname }}

      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.jobname }}.pdf
          name: ${{ matrix.jobname }}_${{ github.ref_name }}
          body: CV Release for version ${{ github.ref_name }}
          draft: false
          prerelease: false