name: Build LaTeX CVs
on:
  push:
    branches:
      - master
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Define default permissions for all jobs in the workflow
permissions:
  contents: read # Needed for checkout in the build job

jobs:
  # --- Build Job ---
  # Compiles both versions of the CV with correct output names and uploads them as artifacts
  build_latex:
    name: Build PDF CVs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile German LaTeX document (DE) as Lebenslauf_Sven_Bergmann.pdf
        run: pdflatex '\def\cvlang{DE}\input{cv.tex}' \
          -jobname=Lebenslauf_Sven_Bergmann

      - name: Compile English LaTeX document (EN) as Curriculum_Vitae_Sven_Bergmann.pdf
        run: pdflatex '\def\cvlang{EN}\input{cv.tex}' \
          -jobname=Curriculum_Vitae_Sven_Bergmann

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            Lebenslauf_Sven_Bergmann.pdf
            Curriculum_Vitae_Sven_Bergmann.pdf

  # --- Release Job ---
  # Creates a GitHub Release and attaches the PDFs (only runs on tag pushes)
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_latex
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download PDF artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: cv-pdfs

      - name: Create Release and Upload PDFs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Lebenslauf_Sven_Bergmann.pdf
            Curriculum_Vitae_Sven_Bergmann.pdf
          name: Release ${{ github.ref_name }}
          body: |
            CV Release for version ${{ github.ref_name }}
            Includes German and English CVs.
          draft: false
          prerelease: false